'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Check, Clock, Copy, CreditCard, ExternalLink, Loader2, QrCode, ShieldCheck, Wallet, Zap } from 'lucide-react';
import { QRCode } from '@/components/QRCode';

type PaymentInvoice = {
  id: string;
  order_id: string | null;
  amount: string;
  currency: string;
  network: string;
  description: string | null;
  status: 'NEW' | 'WAIT' | 'PAID' | 'FAIL' | 'EXPIRED' | 'CANCEL';
  url: string;
  success_url: string | null;
  cancel_url: string | null;
  callback_url: string | null;
  tx_hash: string | null;
  expires_at: string;
  created_at: string;
  paid_at: string | null;
};

export default function PayPage() {
  const params = useParams();
  const paymentId = typeof params?.id === 'string' ? params.id : '';
  const [payment, setPayment] = useState<PaymentInvoice | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const loadPayment = async () => {
    if (!paymentId) return;
    setLoading(true);
    setError('');
    try {
      const response = await fetch(`/api/payments/${paymentId}/status`);
      const data = await response.json();
      if (!response.ok) throw new Error(data.error ?? 'Unable to load payment');
      setPayment(data.payment);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unable to load payment');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadPayment();
    const interval = window.setInterval(loadPayment, 10000);
    return () => window.clearInterval(interval);
  }, [paymentId]);

  const copyPayUrl = async () => {
    if (!payment?.url) return;
    await navigator.clipboard.writeText(payment.url);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1800);
  };

  if (loading && !payment) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-[#070a12] text-white">
        <div className="flex items-center gap-3"><Loader2 className="h-5 w-5 animate-spin" /> Loading payment...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#070a12] text-white">
      <div className="mx-auto flex max-w-6xl flex-col gap-8 px-4 py-10 sm:px-6 lg:px-8">
        <Link href="/" className="inline-flex w-fit items-center gap-2 text-sm font-semibold text-slate-300 transition hover:text-white">
          <ArrowLeft className="h-4 w-4" />
          Back to BlackPayments
        </Link>

        {error && <div className="rounded-3xl border border-rose-400/30 bg-rose-400/10 p-5 text-rose-100">{error}</div>}

        {payment && (
          <section className="rounded-[2rem] border border-white/10 bg-slate-950/70 p-6 shadow-2xl shadow-black/30 sm:p-10">
            <div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between">
              <div>
                <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1 text-xs font-bold text-emerald-300">
                  <ShieldCheck className="h-4 w-4" />
                  BlackPayments payment request
                </div>
                <h1 className="text-3xl font-black tracking-tight text-white sm:text-5xl">Pay securely with crypto</h1>
                <p className="mt-4 max-w-2xl text-slate-300">{payment.description || 'This invoice was generated by BlackPayments and follows the Cryptomus-style payment lifecycle.'}</p>
              </div>
              <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-400 to-indigo-500">
                <Wallet className="h-7 w-7 text-white" />
              </div>
            </div>

            <div className="mt-8 grid gap-4 lg:grid-cols-[1fr_320px]">
              <div className="rounded-3xl border border-white/10 bg-white/[0.035] p-5">
                <div className="flex flex-wrap items-center gap-3">
                  <span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-black text-emerald-300">{payment.status}</span>
                  {payment.order_id && <span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold text-slate-300">Order {payment.order_id}</span>}
                </div>

                <p className="mt-6 text-sm text-slate-400">Payment reference</p>
                <p className="mt-2 break-all font-mono text-sm text-white">{payment.id}</p>

                <div className="mt-6 grid gap-3 sm:grid-cols-3">
                  <div className="rounded-2xl bg-slate-950/60 p-4">
                    <p className="text-xs text-slate-400">Amount</p>
                    <p className="mt-1 text-2xl font-black text-white">{payment.amount} {payment.currency}</p>
                  </div>
                  <div className="rounded-2xl bg-slate-950/60 p-4">
                    <p className="text-xs text-slate-400">Network</p>
                    <p className="mt-1 font-black text-white">{payment.network}</p>
                  </div>
                  <div className="rounded-2xl bg-slate-950/60 p-4">
                    <p className="text-xs text-slate-400">Expires</p>
                    <p className="mt-1 font-black text-white">{new Date(payment.expires_at).toLocaleString()}</p>
                  </div>
                </div>

                {payment.tx_hash && (
                  <div className="mt-5 rounded-2xl border border-white/10 bg-white/[0.035] p-4">
                    <p className="text-sm text-slate-400">Transaction hash</p>
                    <p className="mt-1 break-all font-mono text-sm">{payment.tx_hash}</p>
                  </div>
                )}
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/[0.035] p-5 text-center">
                <QRCode address={payment.url} size={220} showAddress={false} />
                <p className="mt-4 text-sm text-slate-400">Scan to pay or open the payment link</p>
              </div>
            </div>

            <div className="mt-8 rounded-3xl border border-emerald-400/20 bg-emerald-400/10 p-5">
              <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <p className="text-sm font-semibold text-white">Payment link</p>
                  <p className="mt-1 break-all text-sm text-slate-300">{payment.url}</p>
                </div>
                <button onClick={copyPayUrl} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3 font-black text-slate-950 transition hover:bg-slate-200">
                  {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  {copied ? 'Copied' : 'Copy link'}
                </button>
              </div>
            </div>

            <div className="mt-8 grid gap-3 sm:grid-cols-3">
              <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-4">
                <Zap className="h-5 w-5 text-emerald-300" />
                <p className="mt-3 text-sm font-black text-white">Fast settlement</p>
                <p className="mt-1 text-sm text-slate-400">TRON-first USDT payments for low fees and quick confirmations.</p>
              </div>
              <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-4">
                <ShieldCheck className="h-5 w-5 text-emerald-300" />
                <p className="mt-3 text-sm font-black text-white">Webhook-ready</p>
                <p className="mt-1 text-sm text-slate-400">Payment lifecycle events can be delivered to your callback URL.</p>
              </div>
              <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-4">
                <CreditCard className="h-5 w-5 text-emerald-300" />
                <p className="mt-3 text-sm font-black text-white">Merchant API</p>
                <p className="mt-1 text-sm text-slate-400">Create, list, cancel, expire, and check payment status from the API.</p>
              </div>
            </div>
          </section>
        )}

        {!loading && !payment && !error && (
          <section className="rounded-[2rem] border border-white/10 bg-slate-950/70 p-10 text-center">
            <Clock className="mx-auto h-12 w-12 text-slate-400" />
            <h1 className="mt-4 text-3xl font-black">Payment not found</h1>
            <p className="mt-3 text-slate-300">The invoice id is missing or has not been created yet.</p>
            <Link href="/payments" className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-emerald-400 px-6 py-3 font-black text-slate-950">
              Create invoice <ExternalLink className="h-4 w-4" />
            </Link>
          </section>
        )}
      </div>
    </div>
  );
}
